# Generated by Django 6.0.2 on 2026-02-05 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('note_content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('district', models.CharField(max_length=100)),
                ('police_division', models.CharField(blank=True, max_length=100, null=True)),
                ('crime_type', models.CharField(max_length=150)),
                ('crime_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['year', 'month'], name='crime_api_c_year_001984_idx'), models.Index(fields=['district'], name='crime_api_c_distric_186917_idx')],
            },
        ),
    ]
